services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: "laravel-12"
    container_name: ${STAGE_APP_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${STAGE_APP_PORT}:80
    environment:
      APP_ENV_FILE: "stage"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache/ports.conf:/etc/apache2/ports.conf

  redis:
    image: redis:latest
    container_name: ${STAGE_REDIS_CONTAINER_NAME}
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_stage_data:/data

  db:
    image: mysql
    restart: unless-stopped
    container_name: ${STAGE_DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${STAGE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${STAGE_MYSQL_DATABASE}
      MYSQL_USER: ${STAGE_MYSQL_USER}
      MYSQL_PASSWORD: ${STAGE_MYSQL_PASSWORD}
    volumes:
      - laravel_stage_db:/var/lib/mysql

volumes:
  redis_stage_data:
  laravel_stage_db:
