services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: "laravel-12"
    container_name: ${LOCAL_APP_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${LOCAL_APP_PORT}:80
    environment:
      APP_ENV_FILE: "local"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache/ports.conf:/etc/apache2/ports.conf

  redis:
    image: redis:latest
    container_name: ${LOCAL_REDIS_CONTAINER_NAME}
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_local_data:/data

  db:
    image: mysql
    restart: unless-stopped
    container_name: ${LOCAL_DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${LOCAL_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LOCAL_MYSQL_DATABASE}
      MYSQL_USER: ${LOCAL_MYSQL_USER}
      MYSQL_PASSWORD: ${LOCAL_MYSQL_PASSWORD}
    volumes:
      - laravel_local_db:/var/lib/mysql

volumes:
  redis_local_data:
  laravel_local_db:
