services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: "laravel-12"
    container_name: ${PROD_APP_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${PROD_APP_PORT}:80
    environment:
      APP_ENV_FILE: "prod"
    volumes:
      - ./src:/var/www/html
      - ./docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/apache/ports.conf:/etc/apache2/ports.conf

  redis:
    image: redis:latest
    container_name: ${PROD_REDIS_CONTAINER_NAME}
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_prod_data:/data

  db:
    image: mysql
    restart: unless-stopped
    container_name: ${PROD_DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
      MYSQL_USER: ${PROD_MYSQL_USER}
      MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
    volumes:
      - laravel_prod_db:/var/lib/mysql

volumes:
  redis_prod_data:
  laravel_prod_db:
